### ISSUE TITLE
No error catching when RPC server is not reachable

### ISSUE THREAD

**Issue by web3omega** [SolWorks-Dev/soltoolkit-sdk#1]
Currently there is no try/catch when a RPC server is unavailable when invoking `conn` or `connSync`. 
The `ConnectionManager` will not resolve any address and the entire program will crash.

**Comment by web3omega** [comment]
I added a 1 sec timeout and a try/catch here:
[https://github.com/SolWorks-Dev/soltoolkit-sdk/compare/master...web3omega:soltoolkit-sdk:master](https://github.com/SolWorks-Dev/soltoolkit-sdk/compare/master...web3omega:soltoolkit-sdk:master)

**Comment by zhe-t** [comment]
This has been resolved in v0.0.10 (#2). `ConnectionManager` will throw an error if no RPCs are reachable otherwise it will only use reachable RPCs. @web3omega
